webtalk_init -webtalk_dir B:/Vivado_Projects/EEX7436_NEW4/EEX7436_Project/EEX7436_Project.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 20 11:05:19 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4263d588-a119-46c7-914b-4a9622e34281" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3466745b-66c5-4da0-9346-a935baf6d57d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2495 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "11.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key chain -value "0000400023727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400023727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400023727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400023727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Zed/15000000:" -context "labtool\\usage"
webtalk_transmit -clientid 1960004460 -regid "" -xml B:/Vivado_Projects/EEX7436_NEW4/EEX7436_Project/EEX7436_Project.hw/webtalk/usage_statistics_ext_labtool.xml -html B:/Vivado_Projects/EEX7436_NEW4/EEX7436_Project/EEX7436_Project.hw/webtalk/usage_statistics_ext_labtool.html -wdm B:/Vivado_Projects/EEX7436_NEW4/EEX7436_Project/EEX7436_Project.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
