set_property PACKAGE_PIN Y9 [get_ports clk_0]
set_property IOSTANDARD LVCMOS18 [get_ports clk_0]
set_property PACKAGE_PIN R18 [get_ports ctr_rst_0]
set_property IOSTANDARD LVCMOS18 [get_ports ctr_rst_0]
set_property PACKAGE_PIN T22 [get_ports {Actuator_output_value_0[0]}]
set_property PACKAGE_PIN T21 [get_ports {Actuator_output_value_0[1]}]
set_property PACKAGE_PIN U22 [get_ports {Actuator_output_value_0[2]}]
set_property PACKAGE_PIN U21 [get_ports {Actuator_output_value_0[3]}]
set_property PACKAGE_PIN V22 [get_ports {Actuator_output_value_0[4]}]
set_property PACKAGE_PIN W22 [get_ports {Actuator_output_value_0[5]}]
set_property PACKAGE_PIN U19 [get_ports {Actuator_output_value_0[6]}]
set_property PACKAGE_PIN U14 [get_ports {Actuator_output_value_0[7]}]
set_property PACKAGE_PIN A16 [get_ports {Actuator_output_value_0[8]}]
set_property PACKAGE_PIN A17 [get_ports {Actuator_output_value_0[9]}]
set_property PACKAGE_PIN A18 [get_ports {Actuator_output_value_0[10]}]
set_property PACKAGE_PIN A19 [get_ports {Actuator_output_value_0[11]}]
set_property PACKAGE_PIN M15 [get_ports rd_0]
set_property PACKAGE_PIN F22 [get_ports {actuator_rd_index_0[0]}]
set_property PACKAGE_PIN G22 [get_ports {actuator_rd_index_0[1]}]
set_property PACKAGE_PIN H22 [get_ports {actuator_rd_index_0[2]}]
set_property PACKAGE_PIN F21 [get_ports {actuator_rd_index_0[3]}]
set_property PACKAGE_PIN H19 [get_ports {actuator_rd_index_0[4]}]
set_property PACKAGE_PIN H18 [get_ports {actuator_rd_item_0[0]}]
set_property PACKAGE_PIN H17 [get_ports {actuator_rd_item_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Actuator_output_value_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {actuator_rd_item_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {actuator_rd_item_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports rd_0]
set_property IOSTANDARD LVCMOS18 [get_ports {actuator_rd_index_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {actuator_rd_index_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {actuator_rd_index_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {actuator_rd_index_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {actuator_rd_index_0[0]}]
create_clock -period 10.000 -name clk_0 -waveform {0.000 5.000} clk_0

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_0_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {Actuator_output_value_0_OBUF[0]} {Actuator_output_value_0_OBUF[1]} {Actuator_output_value_0_OBUF[2]} {Actuator_output_value_0_OBUF[3]} {Actuator_output_value_0_OBUF[4]} {Actuator_output_value_0_OBUF[5]} {Actuator_output_value_0_OBUF[6]} {Actuator_output_value_0_OBUF[7]} {Actuator_output_value_0_OBUF[8]} {Actuator_output_value_0_OBUF[9]} {Actuator_output_value_0_OBUF[10]} {Actuator_output_value_0_OBUF[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 5 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/Current_state[0]} {design_1_i/Processor_0/U0/CONTROL_U/Current_state[1]} {design_1_i/Processor_0/U0/CONTROL_U/Current_state[2]} {design_1_i/Processor_0/U0/CONTROL_U/Current_state[3]} {design_1_i/Processor_0/U0/CONTROL_U/Current_state[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[0]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[0]_i_2_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[0]_i_3_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[1]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[1]_i_2_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[1]_i_3_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[1]_i_4_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[2]_i_2_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[2]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[3]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[3]_i_2_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[4]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[4]_i_3_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[4]_i_4_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/Processor_0/U0/CONTROL_U/FSM_sequential_Next_state_reg[4]_i_5_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/Processor_0/U0/CONTROL_U/PC_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/Processor_0/U0/CONTROL_U/PC_ld]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/Processor_0/U0/CONTROL_U/PC_rst]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_0_IBUF_BUFG]
